PARAMS = {
    "banana": {
        "env_name": "Banana.app",
        "env_type": "unity",
        "stop_reward": 200,
        "run_name": "banana",
        "replay_size": 100000,
        "replay_initial": 1000,
        "target_net_sync": 100,
        "epsilon_frames": 10 ** 4,
        "epsilon_start": 1.0,
        "epsilon_final": 0.1,
        "learning_rate": 0.001,
        "gamma": 0.99,
        "batch_size": 64,
    },
    "reacher": {
        "env_name": "Reacher.app",
        "env_type": "unity",
        "num_env": 1,
        "num_procs": 1,
        "stop_reward": 195,
        "run_name": "cartpole",
        "replay_size": 100000,
        "replay_initial": 1000,
        "target_net_sync": 100,
        "epsilon_frames": 10 ** 4,
        "epsilon_start": 1.0,
        "epsilon_final": 0.1,
        "learning_rate": 0.001,
        "gamma": 0.99,
        "batch_size": 64,
        "step_count": 4,
        "grad_clip": 5,
        "beta": 0.01,
    },
    "cartpole": {
        "env_name": "CartPole-v0",
        "env_type": "basic",
        "num_env": 2,
        "num_procs": 4,
        "stop_reward": 195,
        "run_name": "cartpole",
        "replay_size": 100000,
        "replay_initial": 1000,
        "target_net_sync": 100,
        "epsilon_frames": 10 ** 4,
        "epsilon_start": 1.0,
        "epsilon_final": 0.1,
        "learning_rate": 0.001,
        "gamma": 0.99,
        "batch_size": 64,
        "step_count": 4,
        "grad_clip": 5,
        "beta": 0.01,
    },
    "pendulum": {
        "env_name": "Pendulum-v0",
        "env_type": "basic",
        "num_env": 2,
        "num_procs": 4,
        "stop_reward": 195,
        "run_name": "cartpole",
        "replay_size": 100000,
        "replay_initial": 1000,
        "target_net_sync": 100,
        "epsilon_frames": 10 ** 4,
        "epsilon_start": 1.0,
        "epsilon_final": 0.1,
        "learning_rate": 0.001,
        "gamma": 0.99,
        "batch_size": 64,
        "step_count": 4,
        "grad_clip": 5,
        "beta": 0.01,
    },
    "lunarlander": {
        "env_name": "LunarLander-v2",
        "env_type": "basic",
        "num_env": 2,
        "num_procs": 4,
        "stop_reward": 200.0,
        "run_name": "lunarlander",
        "replay_size": 100000,
        "replay_initial": 1000,
        "target_net_sync": 100,
        "epsilon_frames": 10 ** 5,
        "epsilon_start": 1.0,
        "epsilon_final": 0.01,
        "learning_rate": 0.001,
        "gamma": 0.99,
        "batch_size": 64,
        "step_count": 4,
        "grad_clip": 5,
        "beta": 0.01,
    },
    "pong": {
        "env_name": "PongNoFrameskip-v4",
        "env_type": "atari",
        "num_env": 2,
        "num_procs": 4,
        "stop_reward": 18.0,
        "run_name": "pong",
        "replay_size": 100000,
        "replay_initial": 10000,
        "target_net_sync": 1000,
        "epsilon_frames": 10 ** 5,
        "epsilon_start": 1.0,
        "epsilon_final": 0.02,
        "learning_rate": 0.0001,
        "gamma": 0.99,
        "batch_size": 32,
        "step_count": 4,
        "grad_clip": 5,
        "beta": 0.01,
    },
}
